version: "3.1"
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: 111111
      POSTGRES_USER: root
      POSTGRES_DB: ractiviti
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
    volumes:
      - db:/var/lib/postgresql/data
  # redis:
  #   restart: always
  #   image: redis
  #   ports:
  #     # 端口映射
  #     - 6379:6379
  #   volumes:
  #     # 持久化 目录映射
  #     - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
  #     - "./redis/data:/data"
  #   command:
  #     # 执行的命令
  #     redis-server /usr/local/etc/redis/redis.conf
volumes:
    db: